host: play.totalfreedom.me
port: 25565
username: username_goes_here
password: password_goes_here
authType: microsoft # microsoft, mojang or offline
buildSyncX: 2021952
buildSyncZ: 17080800
mapartX: -10921088
mapartZ: 648320
maxTiles: 9
commandPrefix: '`'
alternatePrefixes: []
warpName: epsilon_mapart

staffKey: '' # if this value is empty, the UUID-based system is used instead
trustedKey: '' # if this value is empty, the UUID-based system is used instead
trusted:
nonPMCommandsEnabled: true

personalityServerHost: 'http://localhost:8854'
personalityServerAuthToken: 'token_goes_here'
